package com.imagesearch.app.CommonClass;

import android.content.Context;
import android.net.Uri;
import android.os.Environment;

import com.imagesearch.app.database.Models.Images;
import com.imagesearch.app.database.Models.Label;
import com.imagesearch.app.database.Repository.ImagesRepository;
import com.imagesearch.app.database.Repository.LabelRepository;

import org.apache.commons.io.FilenameUtils;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;

import io.realm.Realm;
import io.realm.RealmResults;

public class AppStartup {
    private LabelRepository labelRepository;
    private ImagesRepository imageRepository;
    private Context context;
    private String ExternalStoragePath = Environment.getExternalStorageDirectory().getPath();
    List<Label> labelList;
    List<Images> ImageList;
    Realm db;

    int i = 0;

    public AppStartup(Context context) {
        db = Realm.getDefaultInstance();
        this.context = context;
        this.labelRepository = new LabelRepository();
        this.imageRepository = new ImagesRepository();

        labelList = new ArrayList<Label>();
        ImageList = new ArrayList<Images>();
    }

    public void run() {
        long count = labelRepository.GetCount();
        if (count == 0) {
            setLabels();
        }

        long imagesCount = imageRepository.GetCount();
        if (imagesCount == 0) {
            saveImageDetails();
            imageRepository.Add(ImageList);
        }
    }

    private void saveImageDetails() {
        try {
            SaveImages(ExternalStoragePath);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void SaveImages(String directoryPath) {
        try {
            File[] files = new File(directoryPath).listFiles(new ImageFileFilter());
            for (File file : files) {
                if (file.isDirectory() && file.listFiles(new ImageFileFilter()).length > 0) {
                    SaveImages(file.getAbsolutePath());
                } else {
                    Images img = new Images();
                    img.setId(++i);
                    String extension = FilenameUtils.getExtension(file.getName());

                    if (extension == "" || extension == null) {
                        return;
                    }

                    //Read Creation Date time
                    BasicFileAttributes attr = Files.readAttributes(Paths.get(file.getPath()), BasicFileAttributes.class);
                    img.setName(file.getName());
                    img.setExtension(FilenameUtils.getExtension(file.getName()));
                    img.setUriPath(Uri.fromFile(file).toString());
                    img.setFullPath(file.getAbsolutePath());
                    img.setFileSize(file.length());
                    img.setIsDetectionDone(0);
                    img.setImageCreationDate(new Date(attr.creationTime().to(TimeUnit.MILLISECONDS)));
                    this.ImageList.add(img);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setLabels() {
        try {
            List<String> list = new ArrayList<String>();
            list.add("Bonfire");
            list.add("Comics");
            list.add("Himalayan");
            list.add("Iceberg");
            list.add("Bento");
            list.add("Sink");
            list.add("Toy");
            list.add("Statue");
            list.add("Cheeseburger");
            list.add("Tractor");
            list.add("Sled");
            list.add("Aquarium");
            list.add("Circus");
            list.add("Sitting");
            list.add("Beard");
            list.add("Bridge");
            list.add("Tights");
            list.add("Bird");
            list.add("Rafting");
            list.add("Park");
            list.add("Factory");
            list.add("Graduation");
            list.add("Porcelain");
            list.add("Twig");
            list.add("Petal");
            list.add("Cushion");
            list.add("Sunglasses");
            list.add("Infrastructure");
            list.add("Ferris wheel");
            list.add("Pomacentridae");
            list.add("Wetsuit");
            list.add("Shetland sheepdog");
            list.add("Brig");
            list.add("Watercolor paint");
            list.add("Competition");
            list.add("Cliff");
            list.add("Badminton");
            list.add("Safari");
            list.add("Bicycle");
            list.add("Stadium");
            list.add("Boat");
            list.add("Smile");
            list.add("Surfboard");
            list.add("Fast food");
            list.add("Sunset");
            list.add("Hot dog");
            list.add("Shorts");
            list.add("Bus");
            list.add("Bullfighting");
            list.add("Sky");
            list.add("Gerbil");
            list.add("Rock");
            list.add("Interaction");
            list.add("Dress");
            list.add("Toe");
            list.add("Bear");
            list.add("Eating");
            list.add("Tower");
            list.add("Brick");
            list.add("Junk");
            list.add("Person");
            list.add("Windsurfing");
            list.add("Swimwear");
            list.add("Roller");
            list.add("Camping");
            list.add("Playground");
            list.add("Bathroom");
            list.add("Laugh");
            list.add("Balloon");
            list.add("Concert");
            list.add("Prom");
            list.add("Construction");
            list.add("Product");
            list.add("Reef");
            list.add("Picnic");
            list.add("Wreath");
            list.add("Wheelbarrow");
            list.add("Boxer");
            list.add("Necklace");
            list.add("Bracelet");
            list.add("Casino");
            list.add("Windshield");
            list.add("Stairs");
            list.add("Computer");
            list.add("Cookware and bakeware");
            list.add("Monochrome");
            list.add("Chair");
            list.add("Poster");
            list.add("Bar");
            list.add("Shipwreck");
            list.add("Pier");
            list.add("Community");
            list.add("Caving");
            list.add("Cave");
            list.add("Tie");
            list.add("Cabinetry");
            list.add("Underwater");
            list.add("Clown");
            list.add("Nightclub");
            list.add("Cycling");
            list.add("Comet");
            list.add("Mortarboard");
            list.add("Track");
            list.add("Christmas");
            list.add("Church");
            list.add("Clock");
            list.add("Dude");
            list.add("Cattle");
            list.add("Jungle");
            list.add("Desk");
            list.add("Curling");
            list.add("Cuisine");
            list.add("Cat");
            list.add("Juice");
            list.add("Couscous");
            list.add("Screenshot");
            list.add("Crew");
            list.add("Skyline");
            list.add("Stuffed toy");
            list.add("Cookie");
            list.add("Tile");
            list.add("Hanukkah");
            list.add("Crochet");
            list.add("Skateboarder");
            list.add("Clipper");
            list.add("Nail");
            list.add("Cola");
            list.add("Cutlery");
            list.add("Menu");
            list.add("Sari");
            list.add("Plush");
            list.add("Pocket");
            list.add("Neon");
            list.add("Icicle");
            list.add("Pasteles");
            list.add("Chain");
            list.add("Dance");
            list.add("Dune");
            list.add("Santa claus");
            list.add("Thanksgiving");
            list.add("Tuxedo");
            list.add("Mouth");
            list.add("Desert");
            list.add("Dinosaur");
            list.add("Mufti");
            list.add("Fire");
            list.add("Bedroom");
            list.add("Goggles");
            list.add("Dragon");
            list.add("Couch");
            list.add("Sledding");
            list.add("Cap");
            list.add("Whiteboard");
            list.add("Hat");
            list.add("Gelato");
            list.add("Cavalier");
            list.add("Beanie");
            list.add("Jersey");
            list.add("Scarf");
            list.add("Vacation");
            list.add("Pitch");
            list.add("Blackboard");
            list.add("Deejay");
            list.add("Monument");
            list.add("Bumper");
            list.add("Longboard");
            list.add("Waterfowl");
            list.add("Flesh");
            list.add("Net");
            list.add("Icing");
            list.add("Dalmatian");
            list.add("Speedboat");
            list.add("Trunk");
            list.add("Coffee");
            list.add("Soccer");
            list.add("Ragdoll");
            list.add("Food");
            list.add("Standing");
            list.add("Fiction");
            list.add("Fruit");
            list.add("Pho");
            list.add("Sparkler");
            list.add("Presentation");
            list.add("Swing");
            list.add("Cairn terrier");
            list.add("Forest");
            list.add("Flag");
            list.add("Frigate");
            list.add("Foot");
            list.add("Jacket");
            list.add("Pillow");
            list.add("Bathing");
            list.add("Glacier");
            list.add("Gymnastics");
            list.add("Ear");
            list.add("Flora");
            list.add("Shell");
            list.add("Grandparent");
            list.add("Ruins");
            list.add("Eyelash");
            list.add("Bunk bed");
            list.add("Balance");
            list.add("Backpacking");
            list.add("Horse");
            list.add("Glitter");
            list.add("Saucer");
            list.add("Hair");
            list.add("Miniature");
            list.add("Crowd");
            list.add("Curtain");
            list.add("Icon");
            list.add("Pixie-bob");
            list.add("Herd");
            list.add("Insect");
            list.add("Ice");
            list.add("Bangle");
            list.add("Flap");
            list.add("Jewellery");
            list.add("Knitting");
            list.add("Centrepiece");
            list.add("Outerwear");
            list.add("Love");
            list.add("Muscle");
            list.add("Motorcycle");
            list.add("Money");
            list.add("Mosque");
            list.add("Tableware");
            list.add("Ballroom");
            list.add("Kayak");
            list.add("Leisure");
            list.add("Receipt");
            list.add("Lake");
            list.add("Lighthouse");
            list.add("Bridle");
            list.add("Leather");
            list.add("Horn");
            list.add("Strap");
            list.add("Lego");
            list.add("Scuba diving");
            list.add("Leggings");
            list.add("Pool");
            list.add("Musical instrument");
            list.add("Musical");
            list.add("Metal");
            list.add("Moon");
            list.add("Blazer");
            list.add("Marriage");
            list.add("Mobile phone");
            list.add("Militia");
            list.add("Tablecloth");
            list.add("Party");
            list.add("Nebula");
            list.add("News");
            list.add("Newspaper");
            list.add("Piano");
            list.add("Plant");
            list.add("Passport");
            list.add("Penguin");
            list.add("Shikoku");
            list.add("Palace");
            list.add("Doily");
            list.add("Polo");
            list.add("Paper");
            list.add("Pop music");
            list.add("Skiff");
            list.add("Pizza");
            list.add("Pet");
            list.add("Quilting");
            list.add("Cage");
            list.add("Skateboard");
            list.add("Surfing");
            list.add("Rugby");
            list.add("Lipstick");
            list.add("River");
            list.add("Race");
            list.add("Rowing");
            list.add("Road");
            list.add("Running");
            list.add("Room");
            list.add("Roof");
            list.add("Star");
            list.add("Sports");
            list.add("Shoe");
            list.add("Tubing");
            list.add("Space");
            list.add("Sleep");
            list.add("Skin");
            list.add("Swimming");
            list.add("School");
            list.add("Sushi");
            list.add("Loveseat");
            list.add("Superman");
            list.add("Cool");
            list.add("Skiing");
            list.add("Submarine");
            list.add("Song");
            list.add("Class");
            list.add("Skyscraper");
            list.add("Volcano");
            list.add("Television");
            list.add("Rein");
            list.add("Tattoo");
            list.add("Train");
            list.add("Handrail");
            list.add("Cup");
            list.add("Vehicle");
            list.add("Handbag");
            list.add("Lampshade");
            list.add("Event");
            list.add("Wine");
            list.add("Wing");
            list.add("Wheel");
            list.add("Wakeboarding");
            list.add("Web page");
            list.add("Ranch");
            list.add("Fishing");
            list.add("Heart");
            list.add("Cotton");
            list.add("Cappuccino");
            list.add("Bread");
            list.add("Sand");
            list.add("Museum");
            list.add("Helicopter");
            list.add("Mountain");
            list.add("Duck");
            list.add("Soil");
            list.add("Turtle");
            list.add("Crocodile");
            list.add("Musician");
            list.add("Sneakers");
            list.add("Wool");
            list.add("Ring");
            list.add("Singer");
            list.add("Carnival");
            list.add("Snowboarding");
            list.add("Waterskiing");
            list.add("Wall");
            list.add("Rocket");
            list.add("Countertop");
            list.add("Beach");
            list.add("Rainbow");
            list.add("Branch");
            list.add("Moustache");
            list.add("Garden");
            list.add("Gown");
            list.add("Field");
            list.add("Dog");
            list.add("Superhero");
            list.add("Flower");
            list.add("Placemat");
            list.add("Subwoofer");
            list.add("Cathedral");
            list.add("Building");
            list.add("Airplane");
            list.add("Fur");
            list.add("Bull");
            list.add("Bench");
            list.add("Temple");
            list.add("Butterfly");
            list.add("Model");
            list.add("Marathon");
            list.add("Needlework");
            list.add("Kitchen");
            list.add("Castle");
            list.add("Aurora");
            list.add("Larva");
            list.add("Racing");
            list.add("Airliner");
            list.add("Dam");
            list.add("Textile");
            list.add("Groom");
            list.add("Fun");
            list.add("Steaming");
            list.add("Vegetable");
            list.add("Unicycle");
            list.add("Jeans");
            list.add("Flowerpot");
            list.add("Drawer");
            list.add("Cake");
            list.add("Armrest");
            list.add("Aviation");
            list.add("Fog");
            list.add("Fireworks");
            list.add("Farm");
            list.add("Seal");
            list.add("Shelf");
            list.add("Bangs");
            list.add("Lightning");
            list.add("Van");
            list.add("Sphynx");
            list.add("Tire");
            list.add("Denim");
            list.add("Prairie");
            list.add("Snorkeling");
            list.add("Umbrella");
            list.add("Asphalt");
            list.add("Sailboat");
            list.add("Basset hound");
            list.add("Pattern");
            list.add("Supper");
            list.add("Veil");
            list.add("Waterfall");
            list.add("Lunch");
            list.add("Odometer");
            list.add("Baby");
            list.add("Glasses");
            list.add("Car");
            list.add("Aircraft");
            list.add("Hand");
            list.add("Rodeo");
            list.add("Canyon");
            list.add("Meal");
            list.add("Softball");
            list.add("Alcohol");
            list.add("Bride");
            list.add("Swamp");
            list.add("Pie");
            list.add("Bag");
            list.add("Joker");
            list.add("Supervillain");
            list.add("Army");
            list.add("Canoe");
            list.add("Selfie");
            list.add("Rickshaw");
            list.add("Barn");
            list.add("Archery");
            list.add("Aerospaceengineering");
            list.add("Storm");
            list.add("Helmet");
            list.add("Team");
            List<Label> labelList = new ArrayList<Label>();
            for (int i = 1; i <= list.size(); i++) {
                Label l = new Label();
                l.setId(i);
                l.setLabelName(list.get(i - 1));
                labelList.add(l);
            }

            labelRepository.Add(labelList);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
