package com.imagesearch.app.CommonClass;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.net.Uri;
import android.os.Environment;

import com.imagesearch.app.database.DatabaseInitializer;
import com.imagesearch.app.database.Models.ImageLabelMapping;
import com.imagesearch.app.database.Models.Images;
import com.imagesearch.app.database.Models.Label;
import com.imagesearch.app.database.Repository.ImagesRepository;
import com.imagesearch.app.database.Repository.LabelRepository;

import org.apache.commons.io.FilenameUtils;

import java.io.File;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;

public class AppStartup {

    private LabelRepository labelRepository;
    private ImagesRepository imageRepository;
    private static Context context;
    private static DatabaseInitializer db;
    private String ExternalStoragePath = Environment.getExternalStorageDirectory().getPath();

    public AppStartup(Context context, DatabaseInitializer db) {
        this.context = context;
        this.db = db;
        this.labelRepository = new LabelRepository(db);
        this.imageRepository = new ImagesRepository(db);
    }

    public void run() {
        List<Label> labels = labelRepository.GetLabels();
        if (labels.size() == 0) {
            setLabels();
            saveImageDetails();
        }
    }

    private void saveImageDetails() {
        try {
            SaveImages(ExternalStoragePath);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void SaveImages(String directoryPath) {
        File[] files = new File(directoryPath).listFiles(new ImageFileFilter());
        for (File file : files) {
            if (file.isDirectory() && file.listFiles(new ImageFileFilter()).length > 0) {
                SaveImages(file.getAbsolutePath());
            } else {
                try {
                    Images img = new Images();
                    String extension = FilenameUtils.getExtension(file.getName());

                    if (extension == "" || extension == null) {
                        return;
                    }

                    //Read Creation Date time
                    BasicFileAttributes attr = Files.readAttributes(Paths.get(file.getPath()), BasicFileAttributes.class);
                    img.setName(file.getName());
                    img.setExtension(FilenameUtils.getExtension(file.getName()));
                    img.setUriPath(Uri.fromFile(file).toString());
                    img.setFullPath(file.getAbsolutePath());
                    img.setFileSize(file.length());
                    img.setIsDetectionDone(0);
                    img.setImageCreationDate(new Date(attr.creationTime().to(TimeUnit.MILLISECONDS)));
                    imageRepository.Add(img);
//                    int random = (int) (Math.random() * (10) + 1);
//                    ArrayList randomNumbers = new ArrayList();
//
//                    while (randomNumbers.size() != random) {
//                        int randomLabel = (int) (Math.random() * (100) + 1);
//                        if (!randomNumbers.contains(randomLabel)) {
//                            randomNumbers.add(randomLabel);
//                            ImageLabelMapping map = new ImageLabelMapping();
//                            map.setLabelID(randomLabel);
//                            map.setLabelName("Label " + randomLabel);
//                            map.setImageId(key);
//                            map.setImageName(file.getName());
//                            map.setFullPath(file.getAbsolutePath());
//                            mappingRepository.Add(db, map);
//                        }
//                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }

    private void setLabels() {
        try {
            labelRepository.Add("Bonfire");
            labelRepository.Add("Comics");
            labelRepository.Add("Himalayan");
            labelRepository.Add("Iceberg");
            labelRepository.Add("Bento");
            labelRepository.Add("Sink");
            labelRepository.Add("Toy");
            labelRepository.Add("Statue");
            labelRepository.Add("Cheeseburger");
            labelRepository.Add("Tractor");
            labelRepository.Add("Sled");
            labelRepository.Add("Aquarium");
            labelRepository.Add("Circus");
            labelRepository.Add("Sitting");
            labelRepository.Add("Beard");
            labelRepository.Add("Bridge");
            labelRepository.Add("Tights");
            labelRepository.Add("Bird");
            labelRepository.Add("Rafting");
            labelRepository.Add("Park");
            labelRepository.Add("Factory");
            labelRepository.Add("Graduation");
            labelRepository.Add("Porcelain");
            labelRepository.Add("Twig");
            labelRepository.Add("Petal");
            labelRepository.Add("Cushion");
            labelRepository.Add("Sunglasses");
            labelRepository.Add("Infrastructure");
            labelRepository.Add("Ferris wheel");
            labelRepository.Add("Pomacentridae");
            labelRepository.Add("Wetsuit");
            labelRepository.Add("Shetland sheepdog");
            labelRepository.Add("Brig");
            labelRepository.Add("Watercolor paint");
            labelRepository.Add("Competition");
            labelRepository.Add("Cliff");
            labelRepository.Add("Badminton");
            labelRepository.Add("Safari");
            labelRepository.Add("Bicycle");
            labelRepository.Add("Stadium");
            labelRepository.Add("Boat");
            labelRepository.Add("Smile");
            labelRepository.Add("Surfboard");
            labelRepository.Add("Fast food");
            labelRepository.Add("Sunset");
            labelRepository.Add("Hot dog");
            labelRepository.Add("Shorts");
            labelRepository.Add("Bus");
            labelRepository.Add("Bullfighting");
            labelRepository.Add("Sky");
            labelRepository.Add("Gerbil");
            labelRepository.Add("Rock");
            labelRepository.Add("Interaction");
            labelRepository.Add("Dress");
            labelRepository.Add("Toe");
            labelRepository.Add("Bear");
            labelRepository.Add("Eating");
            labelRepository.Add("Tower");
            labelRepository.Add("Brick");
            labelRepository.Add("Junk");
            labelRepository.Add("Person");
            labelRepository.Add("Windsurfing");
            labelRepository.Add("Swimwear");
            labelRepository.Add("Roller");
            labelRepository.Add("Camping");
            labelRepository.Add("Playground");
            labelRepository.Add("Bathroom");
            labelRepository.Add("Laugh");
            labelRepository.Add("Balloon");
            labelRepository.Add("Concert");
            labelRepository.Add("Prom");
            labelRepository.Add("Construction");
            labelRepository.Add("Product");
            labelRepository.Add("Reef");
            labelRepository.Add("Picnic");
            labelRepository.Add("Wreath");
            labelRepository.Add("Wheelbarrow");
            labelRepository.Add("Boxer");
            labelRepository.Add("Necklace");
            labelRepository.Add("Bracelet");
            labelRepository.Add("Casino");
            labelRepository.Add("Windshield");
            labelRepository.Add("Stairs");
            labelRepository.Add("Computer");
            labelRepository.Add("Cookware and bakeware");
            labelRepository.Add("Monochrome");
            labelRepository.Add("Chair");
            labelRepository.Add("Poster");
            labelRepository.Add("Bar");
            labelRepository.Add("Shipwreck");
            labelRepository.Add("Pier");
            labelRepository.Add("Community");
            labelRepository.Add("Caving");
            labelRepository.Add("Cave");
            labelRepository.Add("Tie");
            labelRepository.Add("Cabinetry");
            labelRepository.Add("Underwater");
            labelRepository.Add("Clown");
            labelRepository.Add("Nightclub");
            labelRepository.Add("Cycling");
            labelRepository.Add("Comet");
            labelRepository.Add("Mortarboard");
            labelRepository.Add("Track");
            labelRepository.Add("Christmas");
            labelRepository.Add("Church");
            labelRepository.Add("Clock");
            labelRepository.Add("Dude");
            labelRepository.Add("Cattle");
            labelRepository.Add("Jungle");
            labelRepository.Add("Desk");
            labelRepository.Add("Curling");
            labelRepository.Add("Cuisine");
            labelRepository.Add("Cat");
            labelRepository.Add("Juice");
            labelRepository.Add("Couscous");
            labelRepository.Add("Screenshot");
            labelRepository.Add("Crew");
            labelRepository.Add("Skyline");
            labelRepository.Add("Stuffed toy");
            labelRepository.Add("Cookie");
            labelRepository.Add("Tile");
            labelRepository.Add("Hanukkah");
            labelRepository.Add("Crochet");
            labelRepository.Add("Skateboarder");
            labelRepository.Add("Clipper");
            labelRepository.Add("Nail");
            labelRepository.Add("Cola");
            labelRepository.Add("Cutlery");
            labelRepository.Add("Menu");
            labelRepository.Add("Sari");
            labelRepository.Add("Plush");
            labelRepository.Add("Pocket");
            labelRepository.Add("Neon");
            labelRepository.Add("Icicle");
            labelRepository.Add("Pasteles");
            labelRepository.Add("Chain");
            labelRepository.Add("Dance");
            labelRepository.Add("Dune");
            labelRepository.Add("Santa claus");
            labelRepository.Add("Thanksgiving");
            labelRepository.Add("Tuxedo");
            labelRepository.Add("Mouth");
            labelRepository.Add("Desert");
            labelRepository.Add("Dinosaur");
            labelRepository.Add("Mufti");
            labelRepository.Add("Fire");
            labelRepository.Add("Bedroom");
            labelRepository.Add("Goggles");
            labelRepository.Add("Dragon");
            labelRepository.Add("Couch");
            labelRepository.Add("Sledding");
            labelRepository.Add("Cap");
            labelRepository.Add("Whiteboard");
            labelRepository.Add("Hat");
            labelRepository.Add("Gelato");
            labelRepository.Add("Cavalier");
            labelRepository.Add("Beanie");
            labelRepository.Add("Jersey");
            labelRepository.Add("Scarf");
            labelRepository.Add("Vacation");
            labelRepository.Add("Pitch");
            labelRepository.Add("Blackboard");
            labelRepository.Add("Deejay");
            labelRepository.Add("Monument");
            labelRepository.Add("Bumper");
            labelRepository.Add("Longboard");
            labelRepository.Add("Waterfowl");
            labelRepository.Add("Flesh");
            labelRepository.Add("Net");
            labelRepository.Add("Icing");
            labelRepository.Add("Dalmatian");
            labelRepository.Add("Speedboat");
            labelRepository.Add("Trunk");
            labelRepository.Add("Coffee");
            labelRepository.Add("Soccer");
            labelRepository.Add("Ragdoll");
            labelRepository.Add("Food");
            labelRepository.Add("Standing");
            labelRepository.Add("Fiction");
            labelRepository.Add("Fruit");
            labelRepository.Add("Pho");
            labelRepository.Add("Sparkler");
            labelRepository.Add("Presentation");
            labelRepository.Add("Swing");
            labelRepository.Add("Cairn terrier");
            labelRepository.Add("Forest");
            labelRepository.Add("Flag");
            labelRepository.Add("Frigate");
            labelRepository.Add("Foot");
            labelRepository.Add("Jacket");
            labelRepository.Add("Pillow");
            labelRepository.Add("Bathing");
            labelRepository.Add("Glacier");
            labelRepository.Add("Gymnastics");
            labelRepository.Add("Ear");
            labelRepository.Add("Flora");
            labelRepository.Add("Shell");
            labelRepository.Add("Grandparent");
            labelRepository.Add("Ruins");
            labelRepository.Add("Eyelash");
            labelRepository.Add("Bunk bed");
            labelRepository.Add("Balance");
            labelRepository.Add("Backpacking");
            labelRepository.Add("Horse");
            labelRepository.Add("Glitter");
            labelRepository.Add("Saucer");
            labelRepository.Add("Hair");
            labelRepository.Add("Miniature");
            labelRepository.Add("Crowd");
            labelRepository.Add("Curtain");
            labelRepository.Add("Icon");
            labelRepository.Add("Pixie-bob");
            labelRepository.Add("Herd");
            labelRepository.Add("Insect");
            labelRepository.Add("Ice");
            labelRepository.Add("Bangle");
            labelRepository.Add("Flap");
            labelRepository.Add("Jewellery");
            labelRepository.Add("Knitting");
            labelRepository.Add("Centrepiece");
            labelRepository.Add("Outerwear");
            labelRepository.Add("Love");
            labelRepository.Add("Muscle");
            labelRepository.Add("Motorcycle");
            labelRepository.Add("Money");
            labelRepository.Add("Mosque");
            labelRepository.Add("Tableware");
            labelRepository.Add("Ballroom");
            labelRepository.Add("Kayak");
            labelRepository.Add("Leisure");
            labelRepository.Add("Receipt");
            labelRepository.Add("Lake");
            labelRepository.Add("Lighthouse");
            labelRepository.Add("Bridle");
            labelRepository.Add("Leather");
            labelRepository.Add("Horn");
            labelRepository.Add("Strap");
            labelRepository.Add("Lego");
            labelRepository.Add("Scuba diving");
            labelRepository.Add("Leggings");
            labelRepository.Add("Pool");
            labelRepository.Add("Musical instrument");
            labelRepository.Add("Musical");
            labelRepository.Add("Metal");
            labelRepository.Add("Moon");
            labelRepository.Add("Blazer");
            labelRepository.Add("Marriage");
            labelRepository.Add("Mobile phone");
            labelRepository.Add("Militia");
            labelRepository.Add("Tablecloth");
            labelRepository.Add("Party");
            labelRepository.Add("Nebula");
            labelRepository.Add("News");
            labelRepository.Add("Newspaper");
            labelRepository.Add("Piano");
            labelRepository.Add("Plant");
            labelRepository.Add("Passport");
            labelRepository.Add("Penguin");
            labelRepository.Add("Shikoku");
            labelRepository.Add("Palace");
            labelRepository.Add("Doily");
            labelRepository.Add("Polo");
            labelRepository.Add("Paper");
            labelRepository.Add("Pop music");
            labelRepository.Add("Skiff");
            labelRepository.Add("Pizza");
            labelRepository.Add("Pet");
            labelRepository.Add("Quilting");
            labelRepository.Add("Cage");
            labelRepository.Add("Skateboard");
            labelRepository.Add("Surfing");
            labelRepository.Add("Rugby");
            labelRepository.Add("Lipstick");
            labelRepository.Add("River");
            labelRepository.Add("Race");
            labelRepository.Add("Rowing");
            labelRepository.Add("Road");
            labelRepository.Add("Running");
            labelRepository.Add("Room");
            labelRepository.Add("Roof");
            labelRepository.Add("Star");
            labelRepository.Add("Sports");
            labelRepository.Add("Shoe");
            labelRepository.Add("Tubing");
            labelRepository.Add("Space");
            labelRepository.Add("Sleep");
            labelRepository.Add("Skin");
            labelRepository.Add("Swimming");
            labelRepository.Add("School");
            labelRepository.Add("Sushi");
            labelRepository.Add("Loveseat");
            labelRepository.Add("Superman");
            labelRepository.Add("Cool");
            labelRepository.Add("Skiing");
            labelRepository.Add("Submarine");
            labelRepository.Add("Song");
            labelRepository.Add("Class");
            labelRepository.Add("Skyscraper");
            labelRepository.Add("Volcano");
            labelRepository.Add("Television");
            labelRepository.Add("Rein");
            labelRepository.Add("Tattoo");
            labelRepository.Add("Train");
            labelRepository.Add("Handrail");
            labelRepository.Add("Cup");
            labelRepository.Add("Vehicle");
            labelRepository.Add("Handbag");
            labelRepository.Add("Lampshade");
            labelRepository.Add("Event");
            labelRepository.Add("Wine");
            labelRepository.Add("Wing");
            labelRepository.Add("Wheel");
            labelRepository.Add("Wakeboarding");
            labelRepository.Add("Web page");
            labelRepository.Add("Ranch");
            labelRepository.Add("Fishing");
            labelRepository.Add("Heart");
            labelRepository.Add("Cotton");
            labelRepository.Add("Cappuccino");
            labelRepository.Add("Bread");
            labelRepository.Add("Sand");
            labelRepository.Add("Museum");
            labelRepository.Add("Helicopter");
            labelRepository.Add("Mountain");
            labelRepository.Add("Duck");
            labelRepository.Add("Soil");
            labelRepository.Add("Turtle");
            labelRepository.Add("Crocodile");
            labelRepository.Add("Musician");
            labelRepository.Add("Sneakers");
            labelRepository.Add("Wool");
            labelRepository.Add("Ring");
            labelRepository.Add("Singer");
            labelRepository.Add("Carnival");
            labelRepository.Add("Snowboarding");
            labelRepository.Add("Waterskiing");
            labelRepository.Add("Wall");
            labelRepository.Add("Rocket");
            labelRepository.Add("Countertop");
            labelRepository.Add("Beach");
            labelRepository.Add("Rainbow");
            labelRepository.Add("Branch");
            labelRepository.Add("Moustache");
            labelRepository.Add("Garden");
            labelRepository.Add("Gown");
            labelRepository.Add("Field");
            labelRepository.Add("Dog");
            labelRepository.Add("Superhero");
            labelRepository.Add("Flower");
            labelRepository.Add("Placemat");
            labelRepository.Add("Subwoofer");
            labelRepository.Add("Cathedral");
            labelRepository.Add("Building");
            labelRepository.Add("Airplane");
            labelRepository.Add("Fur");
            labelRepository.Add("Bull");
            labelRepository.Add("Bench");
            labelRepository.Add("Temple");
            labelRepository.Add("Butterfly");
            labelRepository.Add("Model");
            labelRepository.Add("Marathon");
            labelRepository.Add("Needlework");
            labelRepository.Add("Kitchen");
            labelRepository.Add("Castle");
            labelRepository.Add("Aurora");
            labelRepository.Add("Larva");
            labelRepository.Add("Racing");
            labelRepository.Add("Airliner");
            labelRepository.Add("Dam");
            labelRepository.Add("Textile");
            labelRepository.Add("Groom");
            labelRepository.Add("Fun");
            labelRepository.Add("Steaming");
            labelRepository.Add("Vegetable");
            labelRepository.Add("Unicycle");
            labelRepository.Add("Jeans");
            labelRepository.Add("Flowerpot");
            labelRepository.Add("Drawer");
            labelRepository.Add("Cake");
            labelRepository.Add("Armrest");
            labelRepository.Add("Aviation");
            labelRepository.Add("Fog");
            labelRepository.Add("Fireworks");
            labelRepository.Add("Farm");
            labelRepository.Add("Seal");
            labelRepository.Add("Shelf");
            labelRepository.Add("Bangs");
            labelRepository.Add("Lightning");
            labelRepository.Add("Van");
            labelRepository.Add("Sphynx");
            labelRepository.Add("Tire");
            labelRepository.Add("Denim");
            labelRepository.Add("Prairie");
            labelRepository.Add("Snorkeling");
            labelRepository.Add("Umbrella");
            labelRepository.Add("Asphalt");
            labelRepository.Add("Sailboat");
            labelRepository.Add("Basset hound");
            labelRepository.Add("Pattern");
            labelRepository.Add("Supper");
            labelRepository.Add("Veil");
            labelRepository.Add("Waterfall");
            labelRepository.Add("Lunch");
            labelRepository.Add("Odometer");
            labelRepository.Add("Baby");
            labelRepository.Add("Glasses");
            labelRepository.Add("Car");
            labelRepository.Add("Aircraft");
            labelRepository.Add("Hand");
            labelRepository.Add("Rodeo");
            labelRepository.Add("Canyon");
            labelRepository.Add("Meal");
            labelRepository.Add("Softball");
            labelRepository.Add("Alcohol");
            labelRepository.Add("Bride");
            labelRepository.Add("Swamp");
            labelRepository.Add("Pie");
            labelRepository.Add("Bag");
            labelRepository.Add("Joker");
            labelRepository.Add("Supervillain");
            labelRepository.Add("Army");
            labelRepository.Add("Canoe");
            labelRepository.Add("Selfie");
            labelRepository.Add("Rickshaw");
            labelRepository.Add("Barn");
            labelRepository.Add("Archery");
            labelRepository.Add("Aerospaceengineering");
            labelRepository.Add("Storm");
            labelRepository.Add("Helmet");
            labelRepository.Add("Team");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
